/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;
import java.awt.Color;
import java.awt.Graphics;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *  Covarrubias Solís Víctor Alfonso – 177294
    Puente Sánchez Erick Emmanuel – 174662
 * 
 */
public class MenuAdmins extends javax.swing.JFrame {

    
    
    Connection con;
    public MenuAdmins(Connection c) throws SQLException{//recibe la conexion a la base de datos
        con = c;
        this.setTitle("Menu Admin");
        this.setResizable(false);//para que no se pueda cambiar el tamaño
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Fondo();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnModificarUA = new javax.swing.JButton();
        btnEliminarUA = new javax.swing.JButton();
        registrararticulo = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnPermisos = new javax.swing.JButton();
        registrarproducto = new javax.swing.JButton();
        btnConsultarComApa = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(204, 0, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 24)); // NOI18N
        jLabel1.setText("MENU ADMINISTRADOR");

        btnRegistrar.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistrar.setText("Añadir administrador");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificarUA.setBackground(new java.awt.Color(0, 153, 204));
        btnModificarUA.setText("Modificar users / admins");
        btnModificarUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUAActionPerformed(evt);
            }
        });

        btnEliminarUA.setText("Eliminar users / admins");
        btnEliminarUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUAActionPerformed(evt);
            }
        });

        registrararticulo.setText("Registrar Articulo");
        registrararticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrararticuloActionPerformed(evt);
            }
        });

        btnEliminarProducto.setBackground(new java.awt.Color(0, 153, 204));
        btnEliminarProducto.setText("Eliminar producto");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        btnModificarProducto.setBackground(new java.awt.Color(0, 153, 204));
        btnModificarProducto.setText("Modificar producto");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });

        btnPermisos.setText("Permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });

        registrarproducto.setText("Registrar Producto");
        registrarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarproductoActionPerformed(evt);
            }
        });

        btnConsultarComApa.setBackground(new java.awt.Color(0, 153, 204));
        btnConsultarComApa.setText("Consultar compras / apartados");
        btnConsultarComApa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarComApaActionPerformed(evt);
            }
        });

        btnEstadisticas.setBackground(new java.awt.Color(0, 153, 204));
        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        cerrar.setBackground(new java.awt.Color(0, 153, 204));
        cerrar.setText("Cerrar sesion");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModificarUA, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrararticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarComApa)
                            .addComponent(btnModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarUA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(674, 674, 674))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(333, 333, 333))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(Salir)
                .addGap(18, 18, 18)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarUA)
                    .addComponent(btnRegistrar))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarUA)
                    .addComponent(registrarproducto))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarProducto)
                    .addComponent(btnModificarProducto))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPermisos)
                    .addComponent(registrararticulo))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstadisticas)
                    .addComponent(btnConsultarComApa))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(cerrar))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            new AñadirAdmin(con).setVisible(true);//se abre la ventana de registro de producto
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUAActionPerformed
        try {
            new ModificacionusuariosAdmin(con).setVisible(true);//se abre la ventana de modifcicar datos de usuarios
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_btnModificarUAActionPerformed

    private void btnEliminarUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUAActionPerformed
        try {
            new EliminarUsuarios(con).setVisible(true);
        }catch(SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();
    }//GEN-LAST:event_btnEliminarUAActionPerformed

    private void registrararticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrararticuloActionPerformed
        try {
            new RegistrarArticulo(con).setVisible(true);//se abre la ventana de registro de producto
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_registrararticuloActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        try {
            new EliminarProductos(con).setVisible(true);
        }catch(SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        try {
            new ModificarProducto(con).setVisible(true);//se abre la ventana de registro de producto
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        try {
            new Permisos(con).setVisible(true);//se abre la ventana de registro de producto
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_btnPermisosActionPerformed

    private void registrarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarproductoActionPerformed
        try {
            new RegistrarProducto(con).setVisible(true);//se abre la ventana de registro de producto
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_registrarproductoActionPerformed

    private void btnConsultarComApaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarComApaActionPerformed
        try {
            new ConsultaCompras(con).setVisible(true);//se abre la ventana de registro de producto
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_btnConsultarComApaActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        try {
            new Graficas(con).setVisible(true);//se abre la ventana de registro de producto
        } catch (SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();//se cierra la ventana de login al abrirse la de registro
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Graphics papel = jPanel1.getGraphics();//devuelve un objeto de tipo grafics que se guarda en el objeto papel
        papel.setColor(Color.BLACK);//cambiar color
        papel.fillRect(0, 0, 800, 700);//imprimir rectangulo
        ImageIcon img4 = new ImageIcon(getClass().getResource("/imagenes/salir.png"));
        papel.drawImage(img4.getImage(), 0, 0,getWidth(), getHeight(), this);//se dibuja la imagen de salida
        try {//para parar el tiempo unos cuantos milisegundos
            Thread.sleep(600);
        } catch (InterruptedException e) {
            System.out.println("Error"+ e);
        }
        exit(0);//terminar el programa
    }//GEN-LAST:event_SalirActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        try{
            new Login(con).setVisible(true);
        }catch(SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    class Fondo extends javax.swing.JPanel{//funcion creada para que se cambie el fondo del panel
        private java.awt.Image imagen;//se crea una variable para la imagen del fondo
        @Override//viene de JFrame por eso se sobreescribio
        public void paint(java.awt.Graphics g){//funcion que recibe graficos y sirve para cambiar fondos
            imagen = new javax.swing.ImageIcon(getClass().getResource("/imagenes/menuadmin.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//se dibuja la imagen
            setOpaque(false);
            super.paint(g);//se usa el metodo de la clase padre con super
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton btnConsultarComApa;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnEliminarUA;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnModificarUA;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrararticulo;
    private javax.swing.JButton registrarproducto;
    // End of variables declaration//GEN-END:variables
}
