/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;//para la creacion de la tabla
import javax.swing.JOptionPane;
/**
 *
 * @author victor
 */
public class Misapartados extends javax.swing.JFrame {

    String usuario;
    String cantidad;
    String precio;
    String preciouni;
    Connection con;
    public Misapartados(Connection c, String u)  throws SQLException {
        con = c;
        usuario=u;
        this.setTitle("Mis apartados");
        this.setResizable(false);//para que no se pueda cambiar el tamaño
        this.setVisible(true);//mostrar la ventana
        initComponents();
        actualizartabla();//para que se actualize la tabla
        rellenarcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanel1 = new Fondo();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Menu = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Mis Apartados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Comprar");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Eliminar");

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(Menu))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(430, 430, 430))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(68, 68, 68)
                        .addComponent(jRadioButton2)
                        .addGap(406, 406, 406))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Confirmar)
                        .addGap(467, 467, 467))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Confirmar)
                .addGap(101, 101, 101)
                .addComponent(Menu)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void rellenarcombo(){
        Statement s;
        ResultSet rs;  
        try{
            s = con.createStatement();//se crea un statement sql
            String tablaapartados= ("SELECT * FROM apartados");
            rs= s.executeQuery(tablaapartados);
            
            while(rs.next()){
                jComboBox1.addItem(rs.getString("nomproducto"));
            }
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }
    public void generarPDF(String n, String u, int ca, float p, float pt) throws FileNotFoundException, DocumentException{
        Document documento = new Document();
        FileOutputStream ficheroPDF = new FileOutputStream("ticket.PDF");
        
        PdfWriter.getInstance(documento, ficheroPDF);
        documento.open();
        
        Paragraph titulo = new Paragraph("Ticket de compra \n\n",
                FontFactory.getFont("arial",
                        22,Font.BOLD, BaseColor.BLUE)
        );
        documento.add(titulo);
        PdfPTable tabla = new PdfPTable(5);
        tabla.addCell("Nombre");
        tabla.addCell("Cliente");
        tabla.addCell("Cantidad");
        tabla.addCell("Costo Unitario");
        tabla.addCell("Costo Total");
        tabla.addCell(n);
        tabla.addCell(u);
        tabla.addCell(Integer.toString(ca));
        tabla.addCell(Float.toString(p));
        tabla.addCell(Float.toString(pt));
        
        documento.add(tabla);
        
        documento.close();
    }
    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        try {
            new MenuUser(con, usuario).setVisible(true);
        }catch(SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        if(jRadioButton1.isSelected()){//si lo va a comprar
            try{
                Statement s, s2;
                ResultSet rs;
                
                s = con.createStatement();//se crea un statement sql
                String tablaapartados= ("SELECT * FROM apartados");
                rs= s.executeQuery(tablaapartados);
                while(rs.next()){
                    if(rs.getString("nomproducto").equals(jComboBox1.getSelectedItem().toString())){
                        cantidad=rs.getString("cantidad");
                        precio=rs.getString("costotot");
                        preciouni=rs.getString("costouni");
                    }
                }

                int cantidadtot = Integer.parseInt(cantidad);
                float precio2 = Float.parseFloat(precio);
                float preciouni2 = Float.parseFloat(preciouni);
                s2 = con.createStatement();//se crea un statement sql
                String datosregistro= "INSERT INTO compras (nomproducto, user, cantidad, costouni, costotot)"
                +" VALUES('"+jComboBox1.getSelectedItem().toString()+"','"+usuario+"','"+cantidadtot+"','"+preciouni2+"','"+precio2+"')";//el estado predeterminado del producto sera disponible
                s2.executeUpdate(datosregistro);//se guardan los datos en la tabla productos (la id no se guarda porque se pone sola con la autoincrementacion)
                JOptionPane.showMessageDialog(null, "Comprado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                //se elimina de apartados
                generarPDF(jComboBox1.getSelectedItem().toString(), usuario, cantidadtot, preciouni2, precio2);
                Statement s3 = con.createStatement();//se crea un statement sql
                String eliminacion= ("Delete from apartados WHERE nombre='"+jComboBox1.getSelectedItem().toString()+"'");
                s3.executeUpdate(eliminacion);//se eliminan de la tabla
                jComboBox1.removeAllItems();//se limpia
                rellenarcombo();//se actualiza
            }catch(SQLException e) {
                System.out.println("Error"+e);
            } catch (FileNotFoundException e) {
                System.out.println("Error"+e);
            } catch (DocumentException e) {
                System.out.println("Error"+e);
            }
            
        }
        if(jRadioButton2.isSelected()){//si se va a eliminar
            try{
                Statement s3 = con.createStatement();//se crea un statement sql
                String eliminacion= ("Delete from apartados WHERE nombre='"+jComboBox1.getSelectedItem().toString()+"'");
                s3.executeUpdate(eliminacion);//se eliminan de la tabla
                JOptionPane.showMessageDialog(null, "Eliminado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                jComboBox1.removeAllItems();//se limpia
                rellenarcombo();//se actualiza
            }catch(SQLException e) {
                System.out.println("Error"+e);
            }
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

     public void actualizartabla(){
        Statement s;
        DefaultTableModel modelo = new DefaultTableModel();
        //Encabezados de columnas
        modelo.addColumn("nomproducto");
        modelo.addColumn("user");
        modelo.addColumn("cantidad");
        modelo.addColumn("costouni");
        modelo.addColumn("costotot");

        jTable1.setModel(modelo);
        String datos[] = new String[5];
        
        try{
            
            s = con.createStatement();//se crea un statement sql
            String tablausers= ("Select * from apartados WHERE user='"+usuario+"'");
            ResultSet rs;   
            rs= s.executeQuery(tablausers);
            
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);

                modelo.addRow(datos);
            }
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }
    class Fondo extends javax.swing.JPanel{//funcion creada para que se cambie el fondo del panel
        private java.awt.Image imagen;//se crea una variable para la imagen del fondo
        @Override//viene de JFrame por eso se sobreescribio
        public void paint(java.awt.Graphics g){//funcion que recibe graficos y sirve para cambiar fondos
            imagen = new javax.swing.ImageIcon(getClass().getResource("/imagenes/RegisProducto.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//se dibuja la imagen
            setOpaque(false);
            super.paint(g);//se usa el metodo de la clase padre con super
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton Menu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
