/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *  Covarrubias Solís Víctor Alfonso – 177294
    Puente Sánchez Erick Emmanuel – 174662
 * 
 */
public class RegistrarProducto extends javax.swing.JFrame{
    Connection con;
    //variables para los datos
    static String tipo;
    static String nombre;
    static String anio;
    static String genero;
    static String plataforma;
    static String compania;
    static String precio;
    public RegistrarProducto(Connection c) throws SQLException{//metodo constructor
        con = c;
        this.setTitle("Añadir producto");
        this.setResizable(false);//para que no se pueda cambiar el tamaño
        this.setVisible(true);//mostrar la ventana
        initComponents();
        rellenarcombo();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Fondo();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Registro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        Menu = new javax.swing.JButton();
        Consulta = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Registrar Producto");

        Registro.setText("Registrar");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Cantidad");

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        Consulta.setText("Consultar productos");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Estado");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprar y Apartar", "Solo comprar", "Solo apartar" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(387, 387, 387))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(Consulta)
                .addGap(167, 167, 167))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registro)
                    .addComponent(Consulta)
                    .addComponent(Menu))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void rellenarcombo(){
        Statement s;
        ResultSet rs;
        try{
            s = con.createStatement();//se crea un statement sql
            String tablaproductos= ("SELECT * FROM articulos");
            rs= s.executeQuery(tablaproductos);
            while(rs.next()){
                jComboBox1.addItem(rs.getString("nombre"));
            }
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }
    
    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        //si se presiona el boton
        int cont=0;//para saber si se repitio el producto
        try{//se checa que todos los text fields esten llenos
            if(txtcantidad.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Escribe una cantidad", "ALERTA", JOptionPane.INFORMATION_MESSAGE);
            }else{//si estan todos los datos
                Statement s = con.createStatement();//se crea un statement sql
                String tablaarticulos= ("Select * from articulos");
                s.execute(tablaarticulos);
                ResultSet rs = s.getResultSet();//se guarda el resultado y despues se recorre
                while(rs.next()){//se va recorriendo la tabla srticulos
                    if((rs.getString("nombre").equals(jComboBox1.getSelectedItem().toString()))){//si ya esta en la tabla solo se modifica la cantidad
                        tipo=rs.getString("tipo");
                        nombre=rs.getString("nombre");
                        genero=rs.getString("genero");
                        plataforma=rs.getString("plataforma");
                        compania=rs.getString("compania");
                        anio=rs.getString("anio");
                        precio=rs.getString("precio");
                    }
                }
                Statement s2 = con.createStatement();//se crea un statement sql
                String tablaproductos= ("Select * from productos");
                s2.execute(tablaproductos);
                ResultSet rs2 = s2.getResultSet();//se guarda el resultado y despues se recorre
                while(rs2.next()){//se va recorriendo la tabla productos
                    if((rs2.getString("nombre").equals(jComboBox1.getSelectedItem().toString()))){//si ya esta en la tabla solo se modifica la cantidad
                        //si ya existe en la tabla de productos solo se aumenta la cantidad
                        int cantidadinicial = Integer.parseInt(rs2.getString("cantidad"));
                        int aumento = Integer.parseInt(txtcantidad.getText());
                        Statement s3 = con.createStatement();//se crea un statement sql
                        String datosmodificados= ("UPDATE productos SET cantidad='"+(cantidadinicial+aumento)+"' WHERE nombre='"+nombre+"'");
                        s3.executeUpdate(datosmodificados);//se modifican los datos
                        JOptionPane.showMessageDialog(null, "Como el producto ya se encuentra registrado se le aumento la cantidad", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        //se limpian los campos de los textfields
                        txtcantidad.setText("");
                        //se inicializan las variables
                        nombre="";
                        tipo="";
                        genero="";
                        plataforma="";
                        compania="";
                        anio="";
                        cont++;
                    }
                }
                if(cont==0){//si aun no esta registrado
                    //se copnvierten los datos que se necesitan de manera numerica
                    int anio2 = Integer.parseInt(anio);
                    int cantidad = Integer.parseInt(txtcantidad.getText());
                    float precio2 = Float.parseFloat(precio);
                    Statement s4 = con.createStatement();//se crea un statement sql
                    String datosregistro= "INSERT INTO productos (tipo, nombre, genero, plataforma, compania, anio, cantidad, precio, estado)"
                    +" VALUES('"+tipo+"','"+nombre+"','"+genero+"','"+plataforma+"','"+compania+"','"+anio2+"','"+cantidad+"','"+precio2+"','"+jComboBox2.getSelectedItem().toString()+"')";
                    s4.executeUpdate(datosregistro);//se guardan los datos en la tabla productos (la id no se guarda porque se pone sola con la autoincrementacion)
                    JOptionPane.showMessageDialog(null, "Registro guardado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    //se limpian los campos de los textfields
                    txtcantidad.setText("");
                    //se inicializan las variables
                    nombre="";
                    tipo="";
                    genero="";
                    plataforma="";
                    compania="";
                    anio="";
                } 
            }
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_RegistroActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        try {
            new MenuAdmins(con).setVisible(true);
        }catch(SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
        try {
            new ConsultaProductos(con).setVisible(true);
        }catch(SQLException e) {
            System.out.println("Error"+e);
        }
        this.dispose();
    }//GEN-LAST:event_ConsultaActionPerformed
    
    class Fondo extends javax.swing.JPanel{//funcion creada para que se cambie el fondo del panel
        private java.awt.Image imagen;//se crea una variable para la imagen del fondo
        @Override//viene de JFrame por eso se sobreescribio
        public void paint(java.awt.Graphics g){//funcion que recibe graficos y sirve para cambiar fondos
            imagen = new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrarproducto.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//se dibuja la imagen
            setOpaque(false);
            super.paint(g);//se usa el metodo de la clase padre con super
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consulta;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Registro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}